name: CI
on:
  push: { branches: [ "main" ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Generate coverage badge
        run: coverage-badge -o coverage.svg -f
      - name: Commit coverage badge
        run: |
          if ! git diff --quiet coverage.svg; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add coverage.svg
            git commit -m "chore(ci): update coverage badge"
            git push
          fi
[pytest]
addopts = -q --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=80
testpaths = tests
