# .github/workflows/test.yml
name: test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q

name: CI
on:
  push: { branches: [ "main" ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: { contents: write }  # coverage.svg をコミットするため
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - run: pytest
      - name: Generate coverage badge
        run: coverage-badge -o coverage.svg -f
      - name: Commit coverage badge
        run: |
          if ! git diff --quiet coverage.svg; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add coverage.svg
            git commit -m "chore(ci): update coverage badge"
            git push
          fi
